const fs = require("fs");
const path = require("path");

const BOT_DIR = __dirname;

// A1 words (deduplicated, French-only)
const a1Words = [
  { french: "Bonjour", example: "Bonjour, comment allez-vous ?" },
  { french: "Au revoir", example: "Au revoir et bonne journée !" },
  { french: "Merci", example: "Merci beaucoup pour votre aide." },
  { french: "Oui", example: "Oui, je suis d'accord." },
  { french: "Non", example: "Non, je ne veux pas." },
  { french: "S'il vous plaît", example: "Un café, s'il vous plaît." },
  { french: "Homme", example: "L'homme est dans le jardin." },
  { french: "Femme", example: "La femme lit un livre." },
  { french: "Enfant", example: "L'enfant joue dans le parc." },
  { french: "Ami", example: "Mon ami s'appelle Pierre." },
  { french: "Famille", example: "Ma famille est grande." },
  { french: "Père", example: "Mon père est médecin." },
  { french: "Mère", example: "Ma mère est gentille." },
  { french: "Frère", example: "J'ai un frère." },
  { french: "Soeur", example: "Ma soeur est étudiante." },
  { french: "Fils", example: "Le fils de Marie a dix ans." },
  { french: "Fille", example: "La fille de Pierre est belle." },
  { french: "Mari", example: "Son mari est ingénieur." },
  { french: "Femme", example: "Sa femme est française." },
  { french: "Livre", example: "Le livre est sur la table." },
  { french: "Table", example: "La table est en bois." },
  { french: "Maison", example: "La maison est grande." },
  { french: "École", example: "L'école est à côté." },
  { french: "Travail", example: "Je vais au travail." },
  { french: "Ville", example: "La ville est belle." },
  { french: "Jour", example: "Bonne journée !" },
  { french: "Nuit", example: "Bonne nuit !" },
  { french: "Temps", example: "Quel temps fait-il ?" },
  { french: "Eau", example: "Je bois de l'eau." },
  { french: "Pain", example: "Le pain est frais." },
  { french: "Argent", example: "Je n'ai pas d'argent." },
  { french: "Petit", example: "Le chat est petit." },
  { french: "Grand", example: "La maison est grande." },
  { french: "Bon", example: "C'est un bon restaurant." },
  { french: "Mauvais", example: "Le film est mauvais." },
  { french: "Beau", example: "Quel beau jardin !" },
  { french: "Heureux", example: "Je suis heureux." },
  { french: "Triste", example: "Elle est triste." },
  { french: "Content", example: "Je suis content de mon travail." },
  { french: "Fatigué", example: "Je suis fatigué." },
  { french: "Malade", example: "Il est malade." },
  { french: "Jeune", example: "Il est jeune." },
  { french: "Vieux", example: "La maison est vieille." },
  { french: "Nouveau", example: "J'ai un nouveau téléphone." },
  { french: "Premier", example: "C'est le premier jour." },
  { french: "Dernier", example: "C'est le dernier train." },
  { french: "Cher", example: "C'est trop cher." },
  { french: "Rapide", example: "La voiture est rapide." },
  { french: "Lent", example: "Le train est lent." },
  { french: "Froid", example: "Il fait froid." },
  { french: "Chaud", example: "Il fait chaud." },
  { french: "Difficile", example: "L'examen est difficile." },
  { french: "Facile", example: "C'est facile !" },
  { french: "Important", example: "C'est important." },
  { french: "Parler", example: "Je parle français." },
  { french: "Manger", example: "Je mange du pain." },
  { french: "Boire", example: "Je bois de l'eau." },
  { french: "Dormir", example: "Je dors huit heures." },
  { french: "Lire", example: "Je lis un livre." },
  { french: "Écrire", example: "J'écris une lettre." },
  { french: "Acheter", example: "J'achète du pain." },
  { french: "Vendre", example: "Il vend sa voiture." },
  { french: "Comprendre", example: "Je comprends le français." },
  { french: "Apprendre", example: "J'apprends le français." },
  { french: "Pouvoir", example: "Je peux venir." },
  { french: "Vouloir", example: "Je veux un café." },
  { french: "Devoir", example: "Je dois étudier." },
  { french: "Savoir", example: "Je sais nager." },
  { french: "Venir", example: "Je viens de Paris." },
  { french: "Aller", example: "Je vais à l'école." },
  { french: "Faire", example: "Je fais du sport." },
  { french: "Voir", example: "Je vois la mer." },
  { french: "Mettre", example: "Je mets la table." },
  { french: "Prendre", example: "Je prends le train." },
  { french: "Donner", example: "Je donne un cadeau." },
  { french: "Dire", example: "Je dis bonjour." },
  { french: "Partir", example: "Je pars à huit heures." },
  { french: "Sortir", example: "Je sors avec mes amis." },
  { french: "Rester", example: "Je reste à la maison." },
  { french: "Attendre", example: "J'attends le bus." },
  { french: "Répondre", example: "Je réponds à la question." },
  { french: "Entendre", example: "J'entends la musique." },
  { french: "Monter", example: "Je monte dans le train." },
  { french: "Descendre", example: "Je descends du bus." },
  { french: "Tomber", example: "Il tombe de l'arbre." },
  { french: "Entrer", example: "J'entre dans la salle." },
  { french: "Arriver", example: "J'arrive à la gare." },
  { french: "Habiter", example: "J'habite à Paris." },
  { french: "Travailler", example: "Je travaille dans un bureau." },
  { french: "Étudier", example: "J'étudie le français." },
  { french: "Jouer", example: "Je joue au football." },
  { french: "Chanter", example: "Elle chante bien." },
  { french: "Danser", example: "Nous dansons ensemble." },
  { french: "Cuisiner", example: "Je cuisine le dîner." },
  { french: "Voyager", example: "Je voyage en France." },
  { french: "Nager", example: "Je nage dans la piscine." },
  { french: "Courir", example: "Il court dans le parc." },
  { french: "Pleurer", example: "Pourquoi pleures-tu ?" },
  { french: "Sourire", example: "Elle sourit toujours." },
  { french: "Marcher", example: "Je marche tous les jours." },
  { french: "Porter", example: "Je porte un manteau." },
  { french: "Garder", example: "Garde ton sourire !" },
];

// A2+ words (French-only)
const upperWords = [
  "absolument", "accepter", "accompagner", "achever", "admettre", "adopter",
  "aimable", "ajouter", "allumer", "améliorer", "amener", "amour", "amuser",
  "ancien", "animer", "annoncer", "appareil", "appartenir", "appétit",
  "applaudir", "apporter", "apprécier", "approcher", "appuyer", "arbre",
  "arranger", "article", "assemblée", "asseoir", "assister", "assurer",
  "attacher", "atteindre", "attention", "attraper", "augmenter", "aujourd'hui",
  "autoriser", "avance", "avancer", "avenir", "aventure", "avertir", "avion",
  "avis", "avouer", "bague", "baisser", "balade", "banc", "banque", "barbe",
  "bateau", "bâtiment", "battre", "bavarder", "beauté", "besoin", "bête",
  "bibliothèque", "bientôt", "bijou", "bizarre", "blanc", "blesser", "bleu",
  "blond", "bouche", "bouger", "bouteille", "boutique", "branche", "bruit",
  "brûler", "brun", "bureau", "cabinet", "cacher", "cadeau", "cahier",
  "calculer", "calme", "caméra", "campagne", "capable", "caractère",
  "caresser", "carrefour", "casser", "cause", "célèbre", "centre", "chaîne",
  "chaise", "chaleur", "chambre", "chance", "changer", "chanson", "chapeau",
  "chasser", "chat", "chaussure", "chef", "chemin", "chemise", "chercher",
  "cheval", "cheveu", "chien", "chiffre", "choisir", "chose", "ciel",
  "cinéma", "circulation", "citoyen", "clair", "classe", "client", "climat",
  "coeur", "coiffeur", "colère", "collègue", "colline", "combat", "commander",
  "commencer", "commerce", "commun", "compagnie", "comparer", "complet",
  "composer", "compte", "compter", "condition", "conduire", "conférence",
  "confiance", "confirmer", "conflit", "connaître", "conscience", "conseil",
  "considérer", "construire", "consulter", "contact", "contenir", "continuer",
  "contraire", "contrat", "contrôle", "conversation", "copain", "corps",
  "correct", "corriger", "costume", "coucher", "couleur", "coup", "couper",
  "courage", "courant", "cours", "course", "court", "cousin", "coûter",
  "couvrir", "crayon", "créer", "cri", "crier", "crise", "croire", "cruel",
  "cuillère", "cuir", "cuisine", "cuisinier", "culture", "curieux",
  "danger", "danse", "date", "débat", "début", "décider", "déclarer",
  "décoration", "découper", "découverte", "découvrir", "décrire", "déçu",
  "défaut", "défendre", "défense", "défi", "degré", "déjà", "déjeuner",
  "demain", "demande", "demander", "déménager", "demeurer", "demi", "dent",
  "départ", "dépenser", "déplacer", "depuis", "descendre", "désert",
  "désigner", "désir", "dessin", "dessiner", "détail", "détruire", "dette",
  "deuxième", "développer", "devenir", "diable", "dialogue", "différence",
  "différent", "digne", "dimanche", "dîner", "direct", "direction",
  "diriger", "discours", "disparaître", "disposer", "distance", "distinguer",
  "divers", "docteur", "document", "doigt", "domaine", "domestique",
  "dommage", "donc", "dos", "dossier", "douce", "doucement", "douche",
  "douleur", "doute", "droit", "drôle", "dur", "durant", "durer",
  "échange", "échapper", "échec", "échelle", "économie", "écouter",
  "écraser", "écrit", "éducation", "effacer", "effet", "effort", "égal",
  "église", "élève", "élever", "éloigner", "embrasser", "émission",
  "emmener", "émotion", "emploi", "employer", "emporter", "encourager",
  "endroit", "énergie", "enfance", "enfermer", "enfin", "engagement",
  "enlever", "ennemi", "ennui", "énorme", "enquête", "enregistrer",
  "enseignement", "ensemble", "ensuite", "entendre", "entier", "entourer",
  "entraîner", "entreprise", "entrer", "enveloppe", "envie", "environ",
  "envoyer", "époque", "équipe", "erreur", "escalier", "espace", "espèce",
  "espérer", "espoir", "essai", "essayer", "essence", "essentiel",
  "établir", "étage", "étape", "état", "été", "éteindre", "étendre",
  "étiquette", "étoile", "étonner", "étranger", "étroit", "étude",
  "événement", "éviter", "évolution", "exact", "examiner", "excellent",
  "exception", "excès", "excuse", "exemple", "exercice", "exiger",
  "existence", "expérience", "explication", "expliquer", "exploiter",
  "explorer", "exposer", "exprimer", "extraire", "extrême",
  "fabrication", "face", "façon", "facteur", "faculté", "faible", "faim",
  "fait", "falloir", "fameux", "farce", "fatigue", "faute", "faux",
  "faveur", "féliciter", "fenêtre", "fer", "ferme", "fermer", "fête",
  "feu", "feuille", "fidèle", "fier", "fièvre", "figure", "filet",
  "film", "fin", "final", "finance", "finir", "fixe", "flamme",
  "fleuve", "foi", "foire", "fois", "folie", "fonction", "fond",
  "fonder", "fontaine", "force", "forêt", "forme", "former", "formidable",
  "formule", "fort", "fou", "foule", "four", "fourchette", "fournir",
  "frais", "français", "frapper", "fromage", "front", "fruit", "fuir",
  "fumée", "fumer", "futur", "gagner", "garage", "garçon", "garde",
  "garder", "gare", "gâteau", "gauche", "gel", "général", "genou",
  "genre", "gens", "geste", "glace", "gloire", "goût", "goutte",
  "gouvernement", "grâce", "grain", "grandeur", "grandir", "gratuit",
  "grave", "grimper", "gris", "gros", "groupe", "guerre", "guide",
  "habiller", "habitant", "habitude", "haine", "hasard", "haut",
  "hauteur", "héritage", "herbe", "héros", "heure", "heurter", "hier",
  "histoire", "hiver", "honnête", "honneur", "honte", "hôpital",
  "horloge", "horreur", "hôtel", "huile", "humain", "humeur", "humour",
  "idée", "identique", "identité", "ignorer", "île", "image", "imaginer",
  "immédiat", "immense", "importance", "important", "importer", "imposer",
  "impossible", "impôt", "impression", "imprimer", "incendie", "inclure",
  "inconnu", "incroyable", "indication", "indice", "indiquer", "individu",
  "industrie", "infini", "influence", "information", "informatique",
  "ingénieur", "innocent", "inquiet", "inspirer", "installer", "instant",
  "instinct", "instruction", "instrument", "intelligent", "intense",
  "intention", "interdire", "intéressant", "intérêt", "intérieur",
  "international", "interroger", "interrompre", "intervenir", "intime",
  "introduction", "inutile", "inventer", "invitation", "inviter",
  "jaloux", "jamais", "jambe", "jardin", "jaune", "jeter", "jeu",
  "jeudi", "joie", "joli", "joue", "jouet", "joueur", "journal",
  "journée", "juge", "juger", "juillet", "juin", "jupe", "jurer",
  "jus", "jusque", "juste", "justice",
  "lac", "laid", "laine", "laisser", "lait", "lampe", "lancer",
  "langage", "langue", "large", "larme", "laver", "leçon", "lecture",
  "légal", "légende", "léger", "légume", "lendemain", "lettre",
  "lever", "lèvre", "liberté", "librairie", "libre", "lien", "lier",
  "lieu", "ligne", "limite", "linge", "lion", "liquide", "lisible",
  "liste", "lit", "litre", "livrer", "local", "location", "logement",
  "loi", "loin", "loisir", "long", "longtemps", "lorsque", "louer",
  "lourd", "loyer", "lumière", "lundi", "lune", "lunettes", "lutte",
  "lycée", "machine", "madame", "magnifique", "mai", "main", "maintenant",
  "maître", "mal", "maladie", "malgré", "malheur", "maman", "manche",
  "mandat", "manière", "manifester", "manquer", "manteau", "marchand",
  "marché", "mardi", "marée", "marge", "mariage", "marier", "marin",
  "marque", "marquer", "marron", "marteau", "masse", "matelas",
  "matériel", "matin", "médecin", "médecine", "médicament", "meilleur",
  "mélanger", "membre", "mémoire", "menacer", "ménage", "mener",
  "mensonge", "mental", "mentir", "menu", "mer", "mercredi",
  "mesure", "métier", "mètre", "meuble", "midi", "mieux", "milieu",
  "militaire", "mille", "million", "mince", "ministre", "minuit",
  "minute", "miracle", "miroir", "mission", "mobile", "mode", "modèle",
  "moderne", "modeste", "modifier", "moindre", "moins", "mois",
  "moitié", "moment", "monde", "monnaie", "monsieur", "montagne",
  "monter", "montre", "montrer", "moral", "morceau", "mordre", "mort",
  "mot", "motif", "mou", "mouche", "mouchoir", "mourir", "mouton",
  "mouvement", "moyen", "muet", "mur", "musée", "musique",
  "naissance", "naître", "nation", "nature", "naturel", "navire",
  "nécessaire", "nerveux", "nettoyer", "neuf", "nez", "niveau",
  "Noël", "noir", "nom", "nombre", "nombreux", "nommer",
  "nord", "normal", "note", "noter", "nouer", "nourrir", "nourriture",
  "nouveau", "nouvelle", "nu", "nuage", "nuance", "nuit", "numéro",
  "obéir", "objet", "obligation", "obliger", "obscur", "observer",
  "obstacle", "obtenir", "occasion", "occuper", "océan", "octobre",
  "odeur", "oeil", "oeuvre", "officiel", "offre", "offrir", "oiseau",
  "ombre", "oncle", "ongle", "opéra", "opération", "opinion",
  "opposer", "or", "orage", "orange", "orchestre", "ordinateur",
  "ordre", "oreille", "organisation", "organiser", "orgueil", "orient",
  "original", "oser", "oublier", "ouest", "outil", "ouvert",
  "ouverture", "ouvrage", "ouvrier", "ouvrir", "page", "paille",
  "paire", "paix", "palais", "panier", "panne", "panneau", "papier",
  "paquet", "paraître", "parc", "parcourir", "pardon", "parent",
  "parfait", "parfois", "parfum", "parmi", "parole", "part",
  "partage", "partager", "participer", "partie", "partout", "parvenir",
  "passage", "passer", "passion", "patient", "patron", "patte",
  "pauvre", "pause", "payer", "pays", "paysage", "paysan", "peau",
  "pêche", "peigne", "peindre", "peine", "peintre", "peinture",
  "pendant", "pénétrer", "pensée", "penser", "perdre", "perdu",
  "période", "perle", "permettre", "permis", "personnage", "personne",
  "personnel", "persuader", "perte", "peser", "pétrole", "peu",
  "peuple", "peur", "peut-être", "phare", "phase", "phénomène",
  "philosophie", "photo", "phrase", "physique", "piano", "pièce",
  "pied", "pierre", "pilote", "piscine", "piste", "pitié", "place",
  "placer", "plage", "plaindre", "plaine", "plainte", "plaire",
  "plaisir", "plan", "planche", "planète", "plante", "planter",
  "plat", "plateau", "plein", "pleuvoir", "plonger", "pluie",
  "plume", "plupart", "plutôt", "poche", "poème", "poésie", "poids",
  "poing", "point", "poire", "poison", "poisson", "poitrine",
  "police", "politique", "pomme", "pont", "populaire", "population",
  "port", "portable", "porte", "portefeuille", "portrait", "poser",
  "position", "posséder", "possible", "poste", "poudre", "poule",
  "poulet", "poumon", "pourboire", "pourcentage", "pourtant",
  "pourquoi", "poursuivre", "pousser", "poussière", "pratique",
  "pratiquer", "précautions", "précédent", "précieux", "précipiter",
  "précis", "préférer", "premier", "préparation", "préparer",
  "présence", "présent", "présenter", "président", "presque",
  "presser", "pression", "prêt", "prétendre", "prêter", "preuve",
  "prévenir", "prévoir", "prier", "prière", "prince", "principal",
  "principe", "printemps", "priorité", "prison", "privé", "prix",
  "probable", "problème", "prochain", "proche", "production",
  "produire", "produit", "professeur", "profession", "profiter",
  "profond", "programme", "progrès", "projet", "promenade",
  "promener", "promettre", "promotion", "prononcer", "propos",
  "proposer", "propre", "propriété", "protéger", "prouver",
  "province", "prudent", "public", "publicité",
  "puis", "puisque", "puissance", "punir", "pur",
  "qualité", "quantité", "quarante", "quart", "quartier",
  "quatre", "question", "queue", "quinze", "quitter",
  "quotidien", "race", "racine", "raconter", "raison",
  "ralentir", "ramasser", "ramener", "rang", "ranger", "rapide",
  "rappeler", "rapport", "rapporter", "rare", "rassembler",
  "rayon", "réaction", "réagir", "réalisation", "réaliser",
  "réalité", "recevoir", "réchauffer", "recherche", "rechercher",
  "récit", "réclamation", "réclamer", "récolte", "recommander",
  "recommencer", "récompense", "reconnaître", "record", "récréation",
  "reculer", "rédaction", "redouter", "réduire", "réel", "réfléchir",
  "réflexion", "réforme", "refroidir", "refuge", "refuser", "regard",
  "regarder", "régime", "région", "règle", "régler", "regret",
  "regretter", "régulier", "reine", "rejeter", "rejoindre",
  "relation", "religion", "remarquer", "remercier", "remettre",
  "remonter", "remplacer", "remplir", "rencontre", "rencontrer",
  "rendez-vous", "rendre", "renforcer", "renoncer", "renseignement",
  "rentrer", "renverser", "renvoyer", "repas", "répéter", "répondre",
  "réponse", "repos", "reposer", "reprendre", "représenter",
  "reproche", "réputation", "réseau", "réserver", "résistance",
  "résister", "résoudre", "respect", "respecter", "respirer",
  "responsable", "ressembler", "ressentir", "ressource", "reste",
  "rester", "résultat", "retard", "retenir", "retirer", "retour",
  "retourner", "retraite", "retrouver", "réunion", "réunir",
  "réussir", "réussite", "rêve", "réveil", "réveiller", "révéler",
  "revenir", "rêver", "revoir", "révolution", "riche", "rideau",
  "rien", "rire", "risque", "rivière", "robe", "roche", "rocher",
  "roi", "rue", "ruine", "rythme", "sable", "sac", "saisir",
  "saison", "salaire", "sale", "salle", "salon", "samedi",
  "sang", "santé", "satellite", "satisfaire", "sauter",
  "sauvage", "sauver", "savoir", "scandale", "scène", "science",
  "sculpture", "sec", "sécher", "second", "secret", "secrétaire",
  "secteur", "sécurité", "séduire", "sein", "séjour", "sel",
  "semaine", "semblable", "sembler", "semer", "sens", "sensation",
  "sentier", "sentiment", "sentir", "séparer", "sept", "série",
  "sérieux", "serpent", "serrer", "service", "servir", "serviette",
  "seuil", "seul", "sévère", "siècle", "siège", "signal", "signe",
  "signer", "signifier", "silence", "silencieux", "simple",
  "simplicité", "situation", "six", "social", "société",
  "soeur", "soif", "soin", "soir", "soirée", "soldat", "soleil",
  "solide", "solitude", "solution", "sombre", "somme", "sommeil",
  "sommet", "son", "sondage", "songer", "sonner", "sorte",
  "souci", "soudain", "souffrance", "souffrir", "souhaiter",
  "soulager", "soulever", "souligner", "soumettre", "soupe",
  "sourire", "soutenir", "souvenir", "souvent", "spécial",
  "spectacle", "spectateur", "sport", "sportif", "stade", "stage",
  "station", "statue", "stimuler", "stratégie", "stress",
  "structure", "style", "stylo", "sucre", "sud", "suffire",
  "suffisant", "suggestion", "suite", "suivant", "suivre", "sujet",
  "superbe", "supérieur", "supporter", "supposer", "sûr",
  "surface", "surgir", "surmonter", "surprise", "surtout",
  "surveiller", "symbole", "sympa", "sympathie", "système",
  "tableau", "tablette", "tache", "tâche", "taille", "taire",
  "talent", "tandis", "tant", "tante", "tapis", "tard", "tarif",
  "tasse", "taxe", "technique", "tel", "téléphone", "télévision",
  "témoin", "température", "tempête", "temple", "tendance",
  "tendre", "tenir", "tension", "tentative", "tenter", "terme",
  "terminer", "terrain", "terrasse", "terre", "terrible",
  "territoire", "test", "tête", "texte", "thé", "théâtre",
  "thème", "timbre", "timide", "tirer", "tissu", "titre",
  "toile", "toit", "tomate", "tombe", "ton", "tonne",
  "tort", "tôt", "total", "toucher", "toujours", "tour",
  "tourisme", "touriste", "tourner", "tous", "tout", "toux",
  "tradition", "traduction", "traduire", "train", "trait",
  "traiter", "tranquille", "transformer", "transmettre", "transport",
  "travail", "travers", "traverser", "traitement", "trembler",
  "trentaine", "très", "trésor", "tribu", "tribunal", "tricher",
  "triste", "trois", "troisième", "tromper", "trop", "trottoir",
  "trou", "trouble", "troupe", "trouver", "tuer", "type",
  "univers", "université", "urgence", "usage", "usine", "utiliser",
  "utile", "vacances", "vache", "vague", "vaisselle", "valable",
  "valise", "valeur", "valoir", "vapeur", "vaste",
  "vedette", "véhicule", "veiller", "vendeur", "vendre",
  "vendredi", "vent", "vente", "ventre", "verbe", "vérité",
  "verre", "vers", "verser", "vert", "veste", "vêtement",
  "viande", "victime", "victoire", "vide", "vider", "vie",
  "vieillard", "vieillesse", "vieillir", "vieux", "village",
  "vin", "vingt", "violence", "violent", "violon",
  "visage", "visible", "vision", "visite", "visiter", "visiteur",
  "vite", "vitesse", "vitre", "vivant", "vivre", "vocabulaire",
  "voici", "voie", "voilà", "voile", "voisin", "voiture", "voix",
  "vol", "voler", "volonté", "volume", "vouloir",
  "voyage", "voyager", "voyageur", "vrai", "vue",
  "wagon", "week-end", "yaourt", "zèbre", "zéro", "zone", "zoo",
];

const levels = ["A2", "B1", "B2", "C1", "C2"];
// Build words.json
const allWords = [];
let wordId = 1;
for (const w of a1Words) {
  allWords.push({ id: wordId++, french: w.french, level: "A1", example: w.example });
}
let levelIdx = 0;
let count = 0;
for (const french of upperWords) {
  const level = levels[levelIdx];
  count++;
  if (count >= 120) { count = 0; levelIdx = (levelIdx + 1) % levels.length; }
  const example = `Le mot "${french}" est important.`;
  allWords.push({ id: wordId++, french, level, example });
}

fs.writeFileSync(path.join(BOT_DIR, "words.json"), JSON.stringify(allWords, null, 2));
console.log(`✅ words.json: ${allWords.length} mots`);

// Grammar lessons (French-only)
const allGrammar = [];
let gid = 1;
const a1Grammar = [
  { title: "Les articles définis", explanation: "Les articles définis (le, la, les) sont utilisés pour parler d'une chose spécifique.", examples: ["Le livre est sur la table.", "La maison est grande.", "Les enfants jouent."] },
  { title: "Les articles indéfinis", explanation: "Les articles indéfinis (un, une, des) sont utilisés pour parler d'une chose non spécifique.", examples: ["C'est un ami.", "J'ai une soeur.", "Il y a des livres sur la table."] },
  { title: "Le genre des noms", explanation: "Les noms ont un genre : masculin ou féminin. En général, les noms masculins finissent par une consonne et les noms féminins par -e.", examples: ["Le garçon (masculin)", "La fille (féminin)", "Le livre est sur la table."] },
  { title: "Le pluriel des noms", explanation: "En général, on ajoute -s pour former le pluriel des noms.", examples: ["Un livre → des livres", "Une chaise → des chaises", "Un nez → des nez"] },
  { title: "Le présent - 1er groupe", explanation: "Les verbes en -ER : je -e, tu -es, il/elle -e, nous -ons, vous -ez, ils/elles -ent.", examples: ["Je parle français.", "Tu manges une pomme.", "Il chante bien."] },
  { title: "Le présent - 2e groupe", explanation: "Les verbes en -IR (-issant) : je -is, tu -is, il/elle -it, nous -issons, vous -issez, ils/elles -issent.", examples: ["Je finis mon travail.", "Tu choisis un livre.", "Il réussit l'examen."] },
  { title: "Le présent - 3e groupe", explanation: "Les verbes irréguliers du 3e groupe : être, avoir, aller, faire, etc.", examples: ["Je suis étudiant.", "Tu as un chat.", "Il va à l'école."] },
  { title: "Être et Avoir", explanation: "Les verbes 'être' et 'avoir' sont les deux verbes les plus importants en français.", examples: ["Je suis content.", "Tu es fatigué ?", "Il a faim."] },
  { title: "Aller et Venir", explanation: "Aller (je vais) et Venir (je viens) sont des verbes irréguliers très utilisés.", examples: ["Je vais au marché.", "Tu viens avec moi ?", "Il va à Paris."] },
  { title: "La négation (ne...pas)", explanation: "Pour former la négation, on entoure le verbe par 'ne' et 'pas'.", examples: ["Je ne parle pas anglais.", "Tu ne manges pas ?", "Il ne vient pas."] },
  { title: "L'interrogation", explanation: "Il y a trois façons de poser une question en français.", examples: ["Tu parles français ?", "Parles-tu français ?", "Est-ce que tu parles français ?"] },
  { title: "Les adjectifs possessifs", explanation: "Mon, ton, son, notre, votre, leur s'accordent avec le nom possédé.", examples: ["Mon livre est rouge.", "Ta maison est belle.", "Son chien est petit."] },
  { title: "Les adjectifs démonstratifs", explanation: "Ce, cet, cette, ces servent à montrer quelque chose.", examples: ["Ce livre est intéressant.", "Cet arbre est grand.", "Cette fleur est belle."] },
  { title: "Les prépositions de lieu", explanation: "Sur, sous, dans, devant, derrière, entre indiquent une position.", examples: ["Le livre est sur la table.", "Le chat est sous la chaise.", "La balle est dans le coffre."] },
  { title: "Les nombres 1-100", explanation: "Compter de 1 à 100 en français.", examples: ["J'ai dix euros.", "Il y a vingt étudiants.", "Cent personnes."] },
  { title: "Les couleurs", explanation: "Rouge, bleu, vert, jaune, noir, blanc sont des couleurs de base.", examples: ["Une voiture rouge.", "Le ciel est bleu.", "L'herbe est verte."] },
  { title: "L'heure", explanation: "Pour dire l'heure en français, on utilise 'Il est' + nombre.", examples: ["Il est huit heures.", "Il est midi.", "Il est trois heures et demie."] },
  { title: "Les jours de la semaine", explanation: "Les jours de la semaine : lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche.", examples: ["Aujourd'hui c'est lundi.", "Je travaille le mardi.", "Samedi je me repose."] },
  { title: "Les mois de l'année", explanation: "Janvier, février, mars, avril, mai, juin, juillet, août, septembre, octobre, novembre, décembre.", examples: ["Janvier est le premier mois.", "En été il fait chaud.", "Décembre est le dernier mois."] },
  { title: "La date", explanation: "Pour dire la date en français, on utilise 'Nous sommes le' + nombre + mois.", examples: ["Nous sommes le 1er janvier.", "C'est le 14 juillet.", "Mon anniversaire est le 5 mai."] },
  { title: "Le futur proche", explanation: "Aller + infinitif pour exprimer une action qui va se produire bientôt.", examples: ["Je vais manger.", "Tu vas dormir.", "Il va pleuvoir."] },
  { title: "Le passé récent", explanation: "Venir de + infinitif pour exprimer une action qui vient de se produire.", examples: ["Je viens de manger.", "Tu viens de finir.", "Il vient de partir."] },
  { title: "Les pronoms toniques", explanation: "Moi, toi, lui, elle, nous, vous, eux, elles sont les pronoms toniques.", examples: ["Lui, il est français.", "Moi, je suis marocain.", "Eux, ils sont contents."] },
  { title: "La place des adjectifs", explanation: "La plupart des adjectifs se placent après le nom en français.", examples: ["Une voiture rouge.", "Un homme grand.", "Une belle maison (exceptions)."] },
  { title: "Les verbes pronominaux", explanation: "Les verbes pronominaux se conjuguent avec un pronom réfléchi (me, te, se...).", examples: ["Je me lève à sept heures.", "Tu te laves les mains.", "Il se promène."] },
  { title: "L'impératif", explanation: "L'impératif sert à donner un ordre ou un conseil.", examples: ["Parle plus fort !", "Mangeons ensemble !", "Dormez bien !"] },
  { title: "Les expressions de temps", explanation: "Avant, après, pendant, depuis sont des indicateurs de temps.", examples: ["Avant de manger, je me lave.", "Après l'école, je joue.", "Je travaille depuis huit heures."] },
  { title: "Le partitif", explanation: "Du, de la, de l', des pour exprimer une quantité indéfinie.", examples: ["Je bois du lait.", "Elle mange de la salade.", "Il prend de l'eau."] },
];
const a2Grammar = [
  { title: "Le passé composé avec être", explanation: "Le passé composé avec l'auxiliaire 'être' s'emploie pour 14 verbes de mouvement et les verbes pronominaux.", examples: ["Je suis allé à Paris.", "Elle est partie tôt.", "Ils sont arrivés hier."] },
  { title: "L'imparfait", explanation: "L'imparfait décrit une action passée qui dure, une habitude ou une situation dans le passé.", examples: ["Quand j'étais petit...", "Il faisait beau.", "Je jouais au foot."] },
  { title: "Le futur simple", explanation: "Le futur simple exprime une action future. On ajoute les terminaisons à l'infinitif.", examples: ["Je parlerai demain.", "Tu finiras bientôt.", "Il viendra plus tard."] },
  { title: "Le comparatif", explanation: "Le comparatif permet de comparer deux éléments : plus...que, moins...que, aussi...que.", examples: ["Il est plus grand que moi.", "Elle est moins rapide.", "Il est aussi fort que toi."] },
  { title: "Le superlatif", explanation: "Le superlatif exprime le degré le plus haut ou le plus bas.", examples: ["C'est le plus grand.", "Elle est la plus belle.", "C'est le moins cher."] },
  { title: "Les pronoms COD", explanation: "Les pronoms COD (le, la, les) remplacent un complément d'objet direct.", examples: ["Je vois le chat → Je le vois.", "Elle lit la lettre → Elle la lit.", "Il mange les pommes → Il les mange."] },
  { title: "Les pronoms COI", explanation: "Les pronoms COI (lui, leur) remplacent un complément d'objet indirect.", examples: ["Je parle à Pierre → Je lui parle.", "Il écrit à Marie → Il lui écrit.", "Je téléphone aux parents → Je leur téléphone."] },
  { title: "Le passé récent", explanation: "Venir de + infinitif pour une action qui vient de se produire.", examples: ["Je viens de manger.", "Tu viens de finir.", "Il vient de partir."] },
  { title: "Le futur proche", explanation: "Aller + infinitif pour une action proche dans le futur.", examples: ["Je vais manger.", "Tu vas dormir.", "Il va pleuvoir."] },
  { title: "Les pronoms relatifs qui/que", explanation: "Qui (sujet) et que (objet) relient deux phrases.", examples: ["L'homme qui parle est mon père.", "Le livre que je lis est intéressant.", "La femme que tu vois est ma mère."] },
  { title: "Les pronoms relatifs où/dont", explanation: "Où (lieu/temps) et dont (complément) introduisent une subordonnée.", examples: ["La ville où j'habite est belle.", "Le film dont je parle est connu.", "Le jour où je suis né."] },
  { title: "La voix passive", explanation: "La voix passive se forme avec être + participe passé + par.", examples: ["La lettre est écrite par Marie.", "La maison a été construite.", "Le gâteau est préparé par Paul."] },
  { title: "La cause et la conséquence", explanation: "Parce que, puisque, car (cause). Donc, alors, ainsi (conséquence).", examples: ["Il est fatigué parce qu'il a travaillé.", "Il pleut, donc je reste.", "Puisque tu es là, aide-moi."] },
  { title: "Le but", explanation: "Pour, afin de, dans le but de expriment le but.", examples: ["J'étudie pour réussir.", "Il économise afin d'acheter une voiture.", "Elle travaille pour gagner sa vie."] },
  { title: "Les adverbes de fréquence", explanation: "Toujours, souvent, parfois, rarement, jamais.", examples: ["Je vais souvent au cinéma.", "Il mange parfois au restaurant.", "Elle n'est jamais en retard."] },
  { title: "Les adverbes de manière", explanation: "Bien, mal, vite, lentement, doucement, facilement.", examples: ["Il parle bien français.", "Elle chante mal.", "Il court vite."] },
  { title: "Les prépositions de temps", explanation: "À, dans, en, pendant, depuis, pour, il y a.", examples: ["Je pars à huit heures.", "Il revient dans cinq minutes.", "Je travaille depuis 2010."] },
  { title: "Les nombres ordinaux", explanation: "Premier, deuxième, troisième, quatrième, etc.", examples: ["C'est mon premier jour.", "Il est arrivé deuxième.", "Le troisième étage."] },
  { title: "Les expressions de quantité", explanation: "Beaucoup de, peu de, assez de, trop de, la plupart de.", examples: ["Il y a beaucoup de monde.", "J'ai peu d'argent.", "Il a trop de travail."] },
  { title: "Le gérondif", explanation: "En + participe présent pour exprimer la simultanéité ou la manière.", examples: ["En parlant, il mange.", "Elle chante en travaillant.", "Il lit en mangeant."] },
  { title: "Le discours rapporté au présent", explanation: "Rapporter les paroles de quelqu'un au présent.", examples: ["Il dit qu'il vient.", "Elle annonce qu'elle est prête.", "Ils disent qu'ils partent demain."] },
  { title: "Les indéfinis", explanation: "Quelqu'un, quelque chose, personne, rien, aucun, chaque.", examples: ["Quelqu'un m'attend.", "Je n'ai rien vu.", "Personne n'est venu."] },
  { title: "Les prépositions avec les pays", explanation: "En (féminin), au (masculin), aux (pluriel) pour les pays.", examples: ["Je vais en France.", "Il habite au Canada.", "Elle vient des États-Unis."] },
  { title: "Exprimer l'opinion", explanation: "À mon avis, selon moi, je pense que, je crois que.", examples: ["À mon avis, c'est une bonne idée.", "Je pense qu'il a raison.", "Selon moi, c'est faux."] },
  { title: "Exprimer l'accord et le désaccord", explanation: "Je suis d'accord, je ne suis pas d'accord, tu as raison/tort.", examples: ["Je suis tout à fait d'accord.", "Je ne suis pas d'accord.", "Tu as raison."] },
  { title: "Exprimer la certitude et le doute", explanation: "Je suis sûr, certain, probablement, peut-être, il se peut que.", examples: ["Je suis sûr de cela.", "Il est probablement fatigué.", "Peut-être qu'il viendra."] },
  { title: "Exprimer l'obligation avec 'il faut'", explanation: "Il faut + infinitif ou il faut que + subjonctif.", examples: ["Il faut travailler dur.", "Il faut que tu viennes.", "Il faut partir maintenant."] },
  { title: "Exprimer la possibilité", explanation: "Pouvoir, il est possible de, on peut, il se peut que.", examples: ["Je peux venir demain.", "Il est possible qu'il pleuve.", "On peut sortir ?"] },
];
const b1Grammar = [
  { title: "Le passé composé avec avoir", explanation: "Le passé composé se forme avec l'auxiliaire 'avoir' au présent + le participe passé du verbe.", examples: ["J'ai parlé hier.", "Tu as fini ton travail.", "Il a mangé une pomme."] },
  { title: "Le passé composé avec être", explanation: "Certains verbes utilisent l'auxiliaire 'être' au passé composé. Le participe s'accorde avec le sujet.", examples: ["Je suis allé à Paris.", "Elle est partie tôt.", "Ils sont arrivés hier."] },
  { title: "L'imparfait", explanation: "L'imparfait est utilisé pour les descriptions et les habitudes dans le passé.", examples: ["Quand j'étais petit...", "Il faisait beau.", "Je jouais au foot."] },
  { title: "Passé composé vs Imparfait", explanation: "Le passé composé exprime une action ponctuelle. L'imparfait exprime une description ou une habitude.", examples: ["Il pleuvait quand je suis sorti.", "Je lisais quand tu as téléphoné.", "Il neigeait quand nous sommes arrivés."] },
  { title: "Le futur simple", explanation: "Le futur simple se forme en ajoutant les terminaisons à l'infinitif.", examples: ["Je parlerai demain.", "Tu finiras bientôt.", "Il viendra plus tard."] },
  { title: "Les pronoms COD", explanation: "Le, la, les remplacent un Complément d'Objet Direct.", examples: ["Je vois le chat → Je le vois.", "Elle lit la lettre → Elle la lit.", "Il mange les pommes → Il les mange."] },
  { title: "Les pronoms COI", explanation: "Lui, leur remplacent un Complément d'Objet Indirect.", examples: ["Je parle à Pierre → Je lui parle.", "Il écrit à Marie → Il lui écrit.", "Je téléphone aux parents → Je leur téléphone."] },
  { title: "Le comparatif", explanation: "Plus...que, moins...que, aussi...que pour comparer.", examples: ["Il est plus grand que moi.", "Elle est moins rapide.", "Il est aussi fort que toi."] },
  { title: "Le superlatif", explanation: "Le/la/les plus/moins pour exprimer le degré extrême.", examples: ["C'est le plus grand.", "Elle est la plus belle.", "C'est le moins cher."] },
  { title: "Qui et Que", explanation: "Qui (sujet) et Que (objet) sont des pronoms relatifs.", examples: ["L'homme qui parle est mon père.", "Le livre que je lis est intéressant.", "La femme que tu vois est ma mère."] },
  { title: "Où et Dont", explanation: "Où (lieu/temps) et Dont (complément) sont des pronoms relatifs.", examples: ["La ville où j'habite est belle.", "Le film dont je parle est connu.", "Le jour où je suis né."] },
  { title: "La voix passive", explanation: "Être + participe passé + par pour la forme passive.", examples: ["La lettre est écrite par Marie.", "La maison a été construite.", "Le gâteau est préparé par Paul."] },
  { title: "Le gérondif", explanation: "En + participe présent exprime la simultanéité.", examples: ["En parlant, il mange.", "Elle chante en travaillant.", "Il lit en mangeant."] },
  { title: "Le discours rapporté", explanation: "Rapporter ce que quelqu'un a dit.", examples: ["Il dit qu'il vient.", "Elle a dit qu'elle était fatiguée.", "Ils ont annoncé qu'ils partaient."] },
  { title: "Le plus-que-parfait", explanation: "Avoir/Être à l'imparfait + participe passé pour une action antérieure.", examples: ["J'avais déjà mangé quand tu es arrivé.", "Elle était partie avant moi.", "Ils avaient fini leur travail."] },
  { title: "La cause et la conséquence", explanation: "Parce que, comme, donc, alors expriment la cause et la conséquence.", examples: ["Il est fatigué parce qu'il a travaillé.", "Il pleut, donc je reste à la maison.", "Comme il est tard, je pars."] },
  { title: "Les hypothèses", explanation: "Si + présent, futur simple pour exprimer une hypothèse.", examples: ["Si tu viens, je serai content.", "S'il fait beau, on sortira.", "Si j'ai le temps, je t'aiderai."] },
  { title: "Les pronoms possessifs", explanation: "Le mien, le tien, le sien, etc. remplacent un nom + adjectif possessif.", examples: ["Ce livre est le mien.", "Ta maison est plus grande que la sienne.", "Nos amis et les leurs."] },
  { title: "Les pronoms démonstratifs", explanation: "Celui, celle, ceux, celles remplacent un nom + adjectif démonstratif.", examples: ["Celui-ci est rouge.", "Celle que je préfère est bleue.", "Ceux qui parlent sont mes amis."] },
  { title: "L'opposition et la concession", explanation: "Mais, pourtant, bien que, malgré expriment l'opposition.", examples: ["Il est riche mais il n'est pas heureux.", "Bien qu'il pleuve, je sors.", "Malgré la pluie, je sors."] },
  { title: "Le conditionnel présent", explanation: "Infinitif + terminaisons de l'imparfait pour le conditionnel présent.", examples: ["Je voudrais un café.", "Tu devrais travailler.", "Il pourrait venir."] },
  { title: "Le conditionnel passé", explanation: "Avoir/Être au conditionnel + participe passé.", examples: ["J'aurais voulu venir.", "Tu aurais dû étudier.", "Il serait parti plus tôt."] },
  { title: "Le subjonctif présent", explanation: "Que + verbe au subjonctif pour exprimer le doute, le souhait, la nécessité.", examples: ["Il faut que je parte.", "Je veux que tu viennes.", "Bien qu'il soit fatigué..."] },
  { title: "Le subjonctif passé", explanation: "Avoir/Être au subjonctif + participe passé.", examples: ["Je suis content qu'il ait réussi.", "Il faut que tu sois venu.", "Je doute qu'il ait compris."] },
  { title: "L'interrogation avec inversion", explanation: "Verbe + pronom pour une question formelle.", examples: ["Parlez-vous français ?", "Peut-il venir ?", "Où vont-ils ?"] },
  { title: "Les adverbes de fréquence", explanation: "Toujours, souvent, parfois, rarement, jamais.", examples: ["Je vais souvent au cinéma.", "Il mange parfois au restaurant.", "Elle n'est jamais en retard."] },
  { title: "Les adverbes de manière", explanation: "Bien, mal, vite, lentement, facilement.", examples: ["Il parle bien français.", "Elle chante mal.", "Il court vite."] },
  { title: "Les prépositions de temps", explanation: "À, dans, en, pendant, depuis, pour.", examples: ["Je pars à huit heures.", "Il revient dans cinq minutes.", "Je travaille depuis 2010."] },
  { title: "Les nombres ordinaux", explanation: "Premier, deuxième, troisième, etc.", examples: ["C'est mon premier jour.", "Il est arrivé deuxième.", "Le troisième étage."] },
  { title: "Les expressions de quantité", explanation: "Beaucoup de, peu de, assez de, trop de.", examples: ["Il y a beaucoup de monde.", "J'ai peu d'argent.", "Il a trop de travail."] },
  { title: "Les verbes avec prépositions", explanation: "Penser à, rêver de, commencer par, etc.", examples: ["Je pense à toi.", "Il rêve de voyager.", "Elle commence par lire."] },
  { title: "Les mots de liaison", explanation: "D'abord, ensuite, puis, enfin, finalement.", examples: ["D'abord, je me lève.", "Ensuite, je prends mon café.", "Enfin, je pars au travail."] },
  { title: "Les indéfinis", explanation: "Quelqu'un, quelque chose, personne, rien, aucun.", examples: ["Quelqu'un m'attend.", "Je n'ai rien vu.", "Personne n'est venu."] },
  { title: "Les prépositions avec pays", explanation: "En France, au Maroc, aux États-Unis.", examples: ["Je vais en France.", "Il habite au Canada.", "Elle vient des États-Unis."] },
  { title: "Le verbe plaire", explanation: "Plaire à = faire plaisir, être agréable.", examples: ["Ce film me plaît.", "Tu lui plais.", "Cette chanson plaît à tout le monde."] },
  { title: "Le verbe manquer", explanation: "Manquer à quelqu'un = être absent pour quelqu'un.", examples: ["Tu me manques.", "Il manque à sa famille.", "Paris me manque."] },
  { title: "Les participes présents", explanation: "Formation en -ant.", examples: ["Un homme parlant français.", "Une femme souriante.", "Des enfants jouant."] },
  { title: "Les participes passés", explanation: "Formes régulières et irrégulières.", examples: ["Mangé, fini, vendu, pris, mis.", "Un travail fini.", "Une lettre écrite."] },
  { title: "Le tutoiement et le vouvoiement", explanation: "Tu (informel) vs Vous (formel).", examples: ["Tu vas bien ? (ami)", "Comment allez-vous ?", "Tu veux un café ?"] },
  { title: "Les formules de politesse", explanation: "S'il vous plaît, merci, pardon, excusez-moi.", examples: ["Excusez-moi, où est la gare ?", "Merci beaucoup.", "Je vous en prie."] },
  { title: "Exprimer l'accord et le désaccord", explanation: "Je suis d'accord, pas d'accord, tu as raison.", examples: ["Je suis tout à fait d'accord.", "Je ne suis pas d'accord.", "Tu as raison."] },
  { title: "Exprimer la certitude et le doute", explanation: "Je suis sûr, probablement, peut-être, il se peut que.", examples: ["Je suis sûr de cela.", "Il est probablement fatigué.", "Peut-être qu'il viendra."] },
  { title: "Exprimer l'obligation et l'interdiction", explanation: "Devoir, il faut, interdiction de.", examples: ["Je dois travailler.", "Il faut finir.", "Il est interdit de fumer."] },
  { title: "Exprimer la possibilité", explanation: "Pouvoir, il est possible de, on peut.", examples: ["Je peux venir.", "Il est possible qu'il pleuve.", "On peut sortir ?"] },
  { title: "Exprimer le souhait", explanation: "Je voudrais, j'aimerais, je souhaite.", examples: ["Je voudrais un café.", "J'aimerais voyager.", "Je souhaite réussir."] },
  { title: "Exprimer le regret", explanation: "Je regrette, dommage, si seulement.", examples: ["Je regrette mon erreur.", "Dommage que tu ne viennes pas.", "Si seulement j'avais su."] },
  { title: "Exprimer la joie", explanation: "Je suis heureux, je suis content, je suis ravi.", examples: ["Je suis très heureux.", "Quelle joie de te voir !", "Je suis content de cette nouvelle."] },
  { title: "Exprimer la tristesse", explanation: "Je suis triste, ça me rend triste.", examples: ["Je suis triste de partir.", "Cette nouvelle m'attriste.", "Ça me rend malheureux."] },
  { title: "Exprimer la surprise", explanation: "Je suis surpris, vraiment ?", examples: ["Je suis très surpris !", "Vraiment ? C'est incroyable.", "Quelle surprise !"] },
  { title: "Exprimer la fatigue", explanation: "Je suis fatigué, épuisé, crevé.", examples: ["Je suis fatigué aujourd'hui.", "Je suis épuisé après le travail.", "Je suis crevé !"] },
  { title: "Exprimer l'enthousiasme", explanation: "Super, génial, formidable, excellent.", examples: ["C'est super !", "Quelle idée géniale !", "Formidable, j'adore !"] },
  { title: "Exprimer l'indifférence", explanation: "Ça m'est égal, peu importe.", examples: ["Ça m'est égal.", "Peu importe ce qu'il dit.", "Je m'en fiche."] },
  { title: "Exprimer la satisfaction", explanation: "Je suis satisfait, ça me convient.", examples: ["Je suis satisfait du résultat.", "Ça me convient parfaitement.", "Je suis content de mon travail."] },
  { title: "Exprimer l'insatisfaction", explanation: "Insatisfait, mécontent, déçu.", examples: ["Je suis mécontent du service.", "C'est inacceptable !", "Je ne suis pas satisfait."] },
  { title: "Les verbes d'opinion", explanation: "Croire, penser, trouver, estimer.", examples: ["Je crois qu'il a raison.", "Je pense que c'est juste.", "Je trouve ce film intéressant."] },
  { title: "Les verbes de sentiment", explanation: "Aimer, adorer, détester, préférer.", examples: ["J'aime le chocolat.", "J'adore ce film.", "Je déteste le mensonge."] },
  { title: "Les verbes de perception", explanation: "Voir, entendre, sentir, goûter, toucher.", examples: ["Je vois un oiseau.", "J'entends la musique.", "Je sens le parfum des fleurs."] },
  { title: "Les gallicismes", explanation: "C'est, il y a, voici, voilà sont des expressions typiquement françaises.", examples: ["C'est un ami.", "Il y a un problème.", "Voici mon frère."] },
  { title: "La nominalisation", explanation: "Transformer un verbe en nom.", examples: ["Parler → la parole", "Chanter → le chant", "Danser → la danse"] },
  { title: "L'ordre des pronoms", explanation: "Me/te/se/le/la/les/lui/leur/y/en ont un ordre spécifique.", examples: ["Je le lui donne.", "Il me la montre.", "Donne-le-moi !"] },
  { title: "Les sigles et abréviations", explanation: "SVP, BD, SMS, TV sont des abréviations courantes.", examples: ["Envoie-moi un SMS.", "Je regarde la TV.", "Il lit une BD."] },
  { title: "Les salutations", explanation: "Bonjour, bonsoir, au revoir, salut.", examples: ["Bonjour madame.", "Bonsoir monsieur.", "Salut, ça va ?"] },
  { title: "Demander et donner son avis", explanation: "À mon avis, selon moi, je pense que.", examples: ["À mon avis, c'est une bonne idée.", "Selon moi, il a raison.", "Je pense que oui."] },
  { title: "Exprimer l'obligation avec 'il faut'", explanation: "'Il faut' est suivi de l'infinitif ou du subjonctif.", examples: ["Il faut travailler.", "Il faut que tu viennes.", "Il faut partir maintenant."] },
  { title: "Exprimer l'habitude", explanation: "Avoir l'habitude de, d'habitude, généralement.", examples: ["J'ai l'habitude de me lever tôt.", "D'habitude, je bois du café.", "Généralement, il arrive à l'heure."] },
];
const b2Grammar = [
  { title: "Le subjonctif présent", explanation: "Le subjonctif exprime le doute, le souhait, l'obligation, l'émotion. Il est introduit par 'que'.", examples: ["Il faut que je parte.", "Je veux que tu viennes.", "Bien qu'il soit fatigué."] },
  { title: "Le subjonctif passé", explanation: "Avoir/Être au subjonctif + participe passé pour une action antérieure.", examples: ["Je suis content qu'il ait réussi.", "Il faut que tu sois venu.", "Je doute qu'il ait compris."] },
  { title: "Le conditionnel présent", explanation: "Infinitif + terminaisons de l'imparfait pour exprimer un souhait ou une hypothèse.", examples: ["Je voudrais un café.", "Tu devrais travailler.", "Il pourrait venir."] },
  { title: "Le conditionnel passé", explanation: "Avoir/Être au conditionnel + participe passé pour un regret ou une hypothèse non réalisée.", examples: ["J'aurais voulu venir.", "Tu aurais dû étudier.", "Il serait parti plus tôt."] },
  { title: "Les hypothèses (si + imparfait, conditionnel)", explanation: "Si + imparfait, conditionnel présent pour une hypothèse irréelle.", examples: ["Si j'avais de l'argent, je voyagerais.", "Si tu venais, je serais content.", "S'il faisait beau, on sortirait."] },
  { title: "L'opposition et la concession", explanation: "Bien que, quoique (subjonctif) ; malgré, en dépit de (nom).", examples: ["Bien qu'il pleuve, je sors.", "Malgré la pluie, je sors.", "Quoiqu'il soit tard, je reste."] },
  { title: "Les pronoms démonstratifs", explanation: "Celui, celle, ceux, celles remplacent un nom précédé d'un démonstratif.", examples: ["Celui-ci est rouge.", "Celle que je préfère est bleue.", "Ceux qui parlent sont mes amis."] },
  { title: "Les pronoms possessifs", explanation: "Le mien, le tien, le sien, le nôtre, le vôtre, le leur.", examples: ["Ce livre est le mien.", "Ta maison est plus grande que la sienne.", "Nos amis et les leurs."] },
];
const allGrammarLists = [...a1Grammar, ...a2Grammar, ...b1Grammar, ...b2Grammar];
const levelDist = [];
for (let i = 0; i < a1Grammar.length; i++) levelDist.push("A1");
for (let i = 0; i < a2Grammar.length; i++) levelDist.push("A2");
for (let i = 0; i < b1Grammar.length; i++) levelDist.push("B1");
for (let i = 0; i < b2Grammar.length; i++) levelDist.push("B2");
let gli = 0;
for (const g of allGrammarLists) {
  allGrammar.push({ id: gid++, title: g.title, level: levelDist[gli] || "B1", explanation: g.explanation, examples: g.examples });
  gli++;
}

fs.writeFileSync(path.join(BOT_DIR, "grammar.json"), JSON.stringify(allGrammar, null, 2));
console.log(`✅ grammar.json: ${allGrammar.length} leçons`);

// Verbs (expanded, French-only)
const verbData = [
  { infinitive: "être", level: "A1", present: { je: "suis", tu: "es", "il/elle": "est", nous: "sommes", vous: "êtes", "ils/elles": "sont" }, passe_compose: { je: "ai été", tu: "as été", "il/elle": "a été", nous: "avons été", vous: "avez été", "ils/elles": "ont été" }, imparfait: { je: "étais", tu: "étais", "il/elle": "était", nous: "étions", vous: "étiez", "ils/elles": "étaient" } },
  { infinitive: "avoir", level: "A1", present: { je: "ai", tu: "as", "il/elle": "a", nous: "avons", vous: "avez", "ils/elles": "ont" }, passe_compose: { je: "ai eu", tu: "as eu", "il/elle": "a eu", nous: "avons eu", vous: "avez eu", "ils/elles": "ont eu" }, imparfait: { je: "avais", tu: "avais", "il/elle": "avait", nous: "avions", vous: "aviez", "ils/elles": "avaient" } },
  { infinitive: "aller", level: "A1", present: { je: "vais", tu: "vas", "il/elle": "va", nous: "allons", vous: "allez", "ils/elles": "vont" }, passe_compose: { je: "suis allé", tu: "es allé", "il/elle": "est allé", nous: "sommes allés", vous: "êtes allés", "ils/elles": "sont allés" }, imparfait: { je: "allais", tu: "allais", "il/elle": "allait", nous: "allions", vous: "alliez", "ils/elles": "allaient" } },
  { infinitive: "faire", level: "A1", present: { je: "fais", tu: "fais", "il/elle": "fait", nous: "faisons", vous: "faites", "ils/elles": "font" }, passe_compose: { je: "ai fait", tu: "as fait", "il/elle": "a fait", nous: "avons fait", vous: "avez fait", "ils/elles": "ont fait" }, imparfait: { je: "faisais", tu: "faisais", "il/elle": "faisait", nous: "faisions", vous: "faisiez", "ils/elles": "faisaient" } },
  { infinitive: "parler", level: "A1", present: { je: "parle", tu: "parles", "il/elle": "parle", nous: "parlons", vous: "parlez", "ils/elles": "parlent" }, passe_compose: { je: "ai parlé", tu: "as parlé", "il/elle": "a parlé", nous: "avons parlé", vous: "avez parlé", "ils/elles": "ont parlé" }, imparfait: { je: "parlais", tu: "parlais", "il/elle": "parlait", nous: "parlions", vous: "parliez", "ils/elles": "parlaient" } },
  { infinitive: "finir", level: "A1", present: { je: "finis", tu: "finis", "il/elle": "finit", nous: "finissons", vous: "finissez", "ils/elles": "finissent" }, passe_compose: { je: "ai fini", tu: "as fini", "il/elle": "a fini", nous: "avons fini", vous: "avez fini", "ils/elles": "ont fini" }, imparfait: { je: "finissais", tu: "finissais", "il/elle": "finissait", nous: "finissions", vous: "finissiez", "ils/elles": "finissaient" } },
  { infinitive: "manger", level: "A1", present: { je: "mange", tu: "manges", "il/elle": "mange", nous: "mangeons", vous: "mangez", "ils/elles": "mangent" }, passe_compose: { je: "ai mangé", tu: "as mangé", "il/elle": "a mangé", nous: "avons mangé", vous: "avez mangé", "ils/elles": "ont mangé" }, imparfait: { je: "mangeais", tu: "mangeais", "il/elle": "mangeait", nous: "mangions", vous: "mangiez", "ils/elles": "mangeaient" } },
  { infinitive: "boire", level: "A1", present: { je: "bois", tu: "bois", "il/elle": "boit", nous: "buvons", vous: "buvez", "ils/elles": "boivent" }, passe_compose: { je: "ai bu", tu: "as bu", "il/elle": "a bu", nous: "avons bu", vous: "avez bu", "ils/elles": "ont bu" }, imparfait: { je: "buvais", tu: "buvais", "il/elle": "buvait", nous: "buvions", vous: "buviez", "ils/elles": "buvaient" } },
  { infinitive: "prendre", level: "A1", present: { je: "prends", tu: "prends", "il/elle": "prend", nous: "prenons", vous: "prenez", "ils/elles": "prennent" }, passe_compose: { je: "ai pris", tu: "as pris", "il/elle": "a pris", nous: "avons pris", vous: "avez pris", "ils/elles": "ont pris" }, imparfait: { je: "prenais", tu: "prenais", "il/elle": "prenait", nous: "prenions", vous: "preniez", "ils/elles": "prenaient" } },
  { infinitive: "vouloir", level: "A1", present: { je: "veux", tu: "veux", "il/elle": "veut", nous: "voulons", vous: "voulez", "ils/elles": "veulent" }, passe_compose: { je: "ai voulu", tu: "as voulu", "il/elle": "a voulu", nous: "avons voulu", vous: "avez voulu", "ils/elles": "ont voulu" }, imparfait: { je: "voulais", tu: "voulais", "il/elle": "voulait", nous: "voulions", vous: "vouliez", "ils/elles": "voulaient" } },
  { infinitive: "pouvoir", level: "A1", present: { je: "peux", tu: "peux", "il/elle": "peut", nous: "pouvons", vous: "pouvez", "ils/elles": "peuvent" }, passe_compose: { je: "ai pu", tu: "as pu", "il/elle": "a pu", nous: "avons pu", vous: "avez pu", "ils/elles": "ont pu" }, imparfait: { je: "pouvais", tu: "pouvais", "il/elle": "pouvait", nous: "pouvions", vous: "pouviez", "ils/elles": "pouvaient" } },
  { infinitive: "devoir", level: "A1", present: { je: "dois", tu: "dois", "il/elle": "doit", nous: "devons", vous: "devez", "ils/elles": "doivent" }, passe_compose: { je: "ai dû", tu: "as dû", "il/elle": "a dû", nous: "avons dû", vous: "avez dû", "ils/elles": "ont dû" }, imparfait: { je: "devais", tu: "devais", "il/elle": "devait", nous: "devions", vous: "deviez", "ils/elles": "devaient" } },
  { infinitive: "savoir", level: "A1", present: { je: "sais", tu: "sais", "il/elle": "sait", nous: "savons", vous: "savez", "ils/elles": "savent" }, passe_compose: { je: "ai su", tu: "as su", "il/elle": "a su", nous: "avons su", vous: "avez su", "ils/elles": "ont su" }, imparfait: { je: "savais", tu: "savais", "il/elle": "savait", nous: "savions", vous: "saviez", "ils/elles": "savaient" } },
  { infinitive: "venir", level: "A1", present: { je: "viens", tu: "viens", "il/elle": "vient", nous: "venons", vous: "venez", "ils/elles": "viennent" }, passe_compose: { je: "suis venu", tu: "es venu", "il/elle": "est venu", nous: "sommes venus", vous: "êtes venus", "ils/elles": "sont venus" }, imparfait: { je: "venais", tu: "venais", "il/elle": "venait", nous: "venions", vous: "veniez", "ils/elles": "venaient" } },
  { infinitive: "mettre", level: "A1", present: { je: "mets", tu: "mets", "il/elle": "met", nous: "mettons", vous: "mettez", "ils/elles": "mettent" }, passe_compose: { je: "ai mis", tu: "as mis", "il/elle": "a mis", nous: "avons mis", vous: "avez mis", "ils/elles": "ont mis" }, imparfait: { je: "mettais", tu: "mettais", "il/elle": "mettait", nous: "mettions", vous: "mettiez", "ils/elles": "mettaient" } },
  { infinitive: "dire", level: "A1", present: { je: "dis", tu: "dis", "il/elle": "dit", nous: "disons", vous: "dites", "ils/elles": "disent" }, passe_compose: { je: "ai dit", tu: "as dit", "il/elle": "a dit", nous: "avons dit", vous: "avez dit", "ils/elles": "ont dit" }, imparfait: { je: "disais", tu: "disais", "il/elle": "disait", nous: "disions", vous: "disiez", "ils/elles": "disaient" } },
  { infinitive: "voir", level: "A2", present: { je: "vois", tu: "vois", "il/elle": "voit", nous: "voyons", vous: "voyez", "ils/elles": "voient" }, passe_compose: { je: "ai vu", tu: "as vu", "il/elle": "a vu", nous: "avons vu", vous: "avez vu", "ils/elles": "ont vu" }, imparfait: { je: "voyais", tu: "voyais", "il/elle": "voyait", nous: "voyions", vous: "voyiez", "ils/elles": "voyaient" } },
  { infinitive: "lire", level: "A2", present: { je: "lis", tu: "lis", "il/elle": "lit", nous: "lisons", vous: "lisez", "ils/elles": "lisent" }, passe_compose: { je: "ai lu", tu: "as lu", "il/elle": "a lu", nous: "avons lu", vous: "avez lu", "ils/elles": "ont lu" }, imparfait: { je: "lisais", tu: "lisais", "il/elle": "lisait", nous: "lisions", vous: "lisiez", "ils/elles": "lisaient" } },
  { infinitive: "écrire", level: "A2", present: { je: "écris", tu: "écris", "il/elle": "écrit", nous: "écrivons", vous: "écrivez", "ils/elles": "écrivent" }, passe_compose: { je: "ai écrit", tu: "as écrit", "il/elle": "a écrit", nous: "avons écrit", vous: "avez écrit", "ils/elles": "ont écrit" }, imparfait: { je: "écrivais", tu: "écrivais", "il/elle": "écrivait", nous: "écrivions", vous: "écriviez", "ils/elles": "écrivaient" } },
  { infinitive: "partir", level: "A2", present: { je: "pars", tu: "pars", "il/elle": "part", nous: "partons", vous: "partez", "ils/elles": "partent" }, passe_compose: { je: "suis parti", tu: "es parti", "il/elle": "est parti", nous: "sommes partis", vous: "êtes partis", "ils/elles": "sont partis" }, imparfait: { je: "partais", tu: "partais", "il/elle": "partait", nous: "partions", vous: "partiez", "ils/elles": "partaient" } },
  { infinitive: "sortir", level: "A2", present: { je: "sors", tu: "sors", "il/elle": "sort", nous: "sortons", vous: "sortez", "ils/elles": "sortent" }, passe_compose: { je: "suis sorti", tu: "es sorti", "il/elle": "est sorti", nous: "sommes sortis", vous: "êtes sortis", "ils/elles": "sont sortis" }, imparfait: { je: "sortais", tu: "sortais", "il/elle": "sortait", nous: "sortions", vous: "sortiez", "ils/elles": "sortaient" } },
  { infinitive: "dormir", level: "A2", present: { je: "dors", tu: "dors", "il/elle": "dort", nous: "dormons", vous: "dormez", "ils/elles": "dorment" }, passe_compose: { je: "ai dormi", tu: "as dormi", "il/elle": "a dormi", nous: "avons dormi", vous: "avez dormi", "ils/elles": "ont dormi" }, imparfait: { je: "dormais", tu: "dormais", "il/elle": "dormait", nous: "dormions", vous: "dormiez", "ils/elles": "dormaient" } },
  { infinitive: "connaître", level: "A2", present: { je: "connais", tu: "connais", "il/elle": "connaît", nous: "connaissons", vous: "connaissez", "ils/elles": "connaissent" }, passe_compose: { je: "ai connu", tu: "as connu", "il/elle": "a connu", nous: "avons connu", vous: "avez connu", "ils/elles": "ont connu" }, imparfait: { je: "connaissais", tu: "connaissais", "il/elle": "connaissait", nous: "connaissions", vous: "connaissiez", "ils/elles": "connaissaient" } },
  { infinitive: "vivre", level: "A2", present: { je: "vis", tu: "vis", "il/elle": "vit", nous: "vivons", vous: "vivez", "ils/elles": "vivent" }, passe_compose: { je: "ai vécu", tu: "as vécu", "il/elle": "a vécu", nous: "avons vécu", vous: "avez vécu", "ils/elles": "ont vécu" }, imparfait: { je: "vivais", tu: "vivais", "il/elle": "vivait", nous: "vivions", vous: "viviez", "ils/elles": "vivaient" } },
  { infinitive: "suivre", level: "A2", present: { je: "suis", tu: "suis", "il/elle": "suit", nous: "suivons", vous: "suivez", "ils/elles": "suivent" }, passe_compose: { je: "ai suivi", tu: "as suivi", "il/elle": "a suivi", nous: "avons suivi", vous: "avez suivi", "ils/elles": "ont suivi" }, imparfait: { je: "suivais", tu: "suivais", "il/elle": "suivait", nous: "suivions", vous: "suiviez", "ils/elles": "suivaient" } },
  { infinitive: "rire", level: "A2", present: { je: "ris", tu: "ris", "il/elle": "rit", nous: "rions", vous: "riez", "ils/elles": "rient" }, passe_compose: { je: "ai ri", tu: "as ri", "il/elle": "a ri", nous: "avons ri", vous: "avez ri", "ils/elles": "ont ri" }, imparfait: { je: "riais", tu: "riais", "il/elle": "riait", nous: "riions", vous: "riiez", "ils/elles": "riaient" } },
  { infinitive: "conduire", level: "A2", present: { je: "conduis", tu: "conduis", "il/elle": "conduit", nous: "conduisons", vous: "conduisez", "ils/elles": "conduisent" }, passe_compose: { je: "ai conduit", tu: "as conduit", "il/elle": "a conduit", nous: "avons conduit", vous: "avez conduit", "ils/elles": "ont conduit" }, imparfait: { je: "conduisais", tu: "conduisais", "il/elle": "conduisait", nous: "conduisions", vous: "conduisiez", "ils/elles": "conduisaient" } },
  { infinitive: "croire", level: "A2", present: { je: "crois", tu: "crois", "il/elle": "croit", nous: "croyons", vous: "croyez", "ils/elles": "croient" }, passe_compose: { je: "ai cru", tu: "as cru", "il/elle": "a cru", nous: "avons cru", vous: "avez cru", "ils/elles": "ont cru" }, imparfait: { je: "croyais", tu: "croyais", "il/elle": "croyait", nous: "croyions", vous: "croyiez", "ils/elles": "croyaient" } },
  { infinitive: "courir", level: "A2", present: { je: "cours", tu: "cours", "il/elle": "court", nous: "courons", vous: "courez", "ils/elles": "courent" }, passe_compose: { je: "ai couru", tu: "as couru", "il/elle": "a couru", nous: "avons couru", vous: "avez couru", "ils/elles": "ont couru" }, imparfait: { je: "courais", tu: "courais", "il/elle": "courait", nous: "courions", vous: "couriez", "ils/elles": "couraient" } },
  { infinitive: "envoyer", level: "A2", present: { je: "envoie", tu: "envoies", "il/elle": "envoie", nous: "envoyons", vous: "envoyez", "ils/elles": "envoient" }, passe_compose: { je: "ai envoyé", tu: "as envoyé", "il/elle": "a envoyé", nous: "avons envoyé", vous: "avez envoyé", "ils/elles": "ont envoyé" }, imparfait: { je: "envoyais", tu: "envoyais", "il/elle": "envoyait", nous: "envoyions", vous: "envoyiez", "ils/elles": "envoyaient" } },
  { infinitive: "essayer", level: "A2", present: { je: "essaie", tu: "essaies", "il/elle": "essaie", nous: "essayons", vous: "essayez", "ils/elles": "essaient" }, passe_compose: { je: "ai essayé", tu: "as essayé", "il/elle": "a essayé", nous: "avons essayé", vous: "avez essayé", "ils/elles": "ont essayé" }, imparfait: { je: "essayais", tu: "essayais", "il/elle": "essayait", nous: "essayions", vous: "essayiez", "ils/elles": "essayaient" } },
  { infinitive: "jouer", level: "A1", present: { je: "joue", tu: "joues", "il/elle": "joue", nous: "jouons", vous: "jouez", "ils/elles": "jouent" }, passe_compose: { je: "ai joué", tu: "as joué", "il/elle": "a joué", nous: "avons joué", vous: "avez joué", "ils/elles": "ont joué" }, imparfait: { je: "jouais", tu: "jouais", "il/elle": "jouait", nous: "jouions", vous: "jouiez", "ils/elles": "jouaient" } },
  { infinitive: "chanter", level: "A1", present: { je: "chante", tu: "chantes", "il/elle": "chante", nous: "chantons", vous: "chantez", "ils/elles": "chantent" }, passe_compose: { je: "ai chanté", tu: "as chanté", "il/elle": "a chanté", nous: "avons chanté", vous: "avez chanté", "ils/elles": "ont chanté" }, imparfait: { je: "chantais", tu: "chantais", "il/elle": "chantait", nous: "chantions", vous: "chantiez", "ils/elles": "chantaient" } },
  { infinitive: "monter", level: "A1", present: { je: "monte", tu: "montes", "il/elle": "monte", nous: "montons", vous: "montez", "ils/elles": "montent" }, passe_compose: { je: "suis monté", tu: "es monté", "il/elle": "est monté", nous: "sommes montés", vous: "êtes montés", "ils/elles": "sont montés" }, imparfait: { je: "montais", tu: "montais", "il/elle": "montait", nous: "montions", vous: "montiez", "ils/elles": "montaient" } },
  { infinitive: "descendre", level: "A1", present: { je: "descends", tu: "descends", "il/elle": "descend", nous: "descendons", vous: "descendez", "ils/elles": "descendent" }, passe_compose: { je: "suis descendu", tu: "es descendu", "il/elle": "est descendu", nous: "sommes descendus", vous: "êtes descendus", "ils/elles": "sont descendus" }, imparfait: { je: "descendais", tu: "descendais", "il/elle": "descendait", nous: "descendions", vous: "descendiez", "ils/elles": "descendaient" } },
  { infinitive: "tomber", level: "A1", present: { je: "tombe", tu: "tombes", "il/elle": "tombe", nous: "tombons", vous: "tombez", "ils/elles": "tombent" }, passe_compose: { je: "suis tombé", tu: "es tombé", "il/elle": "est tombé", nous: "sommes tombés", vous: "êtes tombés", "ils/elles": "sont tombés" }, imparfait: { je: "tombais", tu: "tombais", "il/elle": "tombait", nous: "tombions", vous: "tombiez", "ils/elles": "tombaient" } },
  { infinitive: "acheter", level: "A1", present: { je: "achète", tu: "achètes", "il/elle": "achète", nous: "achetons", vous: "achetez", "ils/elles": "achètent" }, passe_compose: { je: "ai acheté", tu: "as acheté", "il/elle": "a acheté", nous: "avons acheté", vous: "avez acheté", "ils/elles": "ont acheté" }, imparfait: { je: "achetais", tu: "achetais", "il/elle": "achetait", nous: "achetions", vous: "achetiez", "ils/elles": "achetaient" } },
  { infinitive: "appeler", level: "A1", present: { je: "appelle", tu: "appelles", "il/elle": "appelle", nous: "appelons", vous: "appelez", "ils/elles": "appellent" }, passe_compose: { je: "ai appelé", tu: "as appelé", "il/elle": "a appelé", nous: "avons appelé", vous: "avez appelé", "ils/elles": "ont appelé" }, imparfait: { je: "appelais", tu: "appelais", "il/elle": "appelait", nous: "appelions", vous: "appeliez", "ils/elles": "appelaient" } },
  { infinitive: "commencer", level: "A1", present: { je: "commence", tu: "commences", "il/elle": "commence", nous: "commençons", vous: "commencez", "ils/elles": "commencent" }, passe_compose: { je: "ai commencé", tu: "as commencé", "il/elle": "a commencé", nous: "avons commencé", vous: "avez commencé", "ils/elles": "ont commencé" }, imparfait: { je: "commençais", tu: "commençais", "il/elle": "commençait", nous: "commencions", vous: "commenciez", "ils/elles": "commençaient" } },
  { infinitive: "payer", level: "A1", present: { je: "paie", tu: "paies", "il/elle": "paie", nous: "payons", vous: "payez", "ils/elles": "paient" }, passe_compose: { je: "ai payé", tu: "as payé", "il/elle": "a payé", nous: "avons payé", vous: "avez payé", "ils/elles": "ont payé" }, imparfait: { je: "payais", tu: "payais", "il/elle": "payait", nous: "payions", vous: "payiez", "ils/elles": "payaient" } },
  { infinitive: "nettoyer", level: "A2", present: { je: "nettoie", tu: "nettoies", "il/elle": "nettoie", nous: "nettoyons", vous: "nettoyez", "ils/elles": "nettoient" }, passe_compose: { je: "ai nettoyé", tu: "as nettoyé", "il/elle": "a nettoyé", nous: "avons nettoyé", vous: "avez nettoyé", "ils/elles": "ont nettoyé" }, imparfait: { je: "nettoyais", tu: "nettoyais", "il/elle": "nettoyait", nous: "nettoyions", vous: "nettoyiez", "ils/elles": "nettoyaient" } },
  { infinitive: "employer", level: "A2", present: { je: "emploie", tu: "emploies", "il/elle": "emploie", nous: "employons", vous: "employez", "ils/elles": "emploient" }, passe_compose: { je: "ai employé", tu: "as employé", "il/elle": "a employé", nous: "avons employé", vous: "avez employé", "ils/elles": "ont employé" }, imparfait: { je: "employais", tu: "employais", "il/elle": "employait", nous: "employions", vous: "employiez", "ils/elles": "employaient" } },
  { infinitive: "avancer", level: "A2", present: { je: "avance", tu: "avances", "il/elle": "avance", nous: "avançons", vous: "avancez", "ils/elles": "avancent" }, passe_compose: { je: "ai avancé", tu: "as avancé", "il/elle": "a avancé", nous: "avons avancé", vous: "avez avancé", "ils/elles": "ont avancé" }, imparfait: { je: "avançais", tu: "avançais", "il/elle": "avançait", nous: "avancions", vous: "avanciez", "ils/elles": "avançaient" } },
  { infinitive: "prononcer", level: "A2", present: { je: "prononce", tu: "prononces", "il/elle": "prononce", nous: "prononçons", vous: "prononcez", "ils/elles": "prononcent" }, passe_compose: { je: "ai prononcé", tu: "as prononcé", "il/elle": "a prononcé", nous: "avons prononcé", vous: "avez prononcé", "ils/elles": "ont prononcé" }, imparfait: { je: "prononçais", tu: "prononçais", "il/elle": "prononçait", nous: "prononcions", vous: "prononciez", "ils/elles": "prononçaient" } },
  { infinitive: "servir", level: "B1", present: { je: "sers", tu: "sers", "il/elle": "sert", nous: "servons", vous: "servez", "ils/elles": "servent" }, passe_compose: { je: "ai servi", tu: "as servi", "il/elle": "a servi", nous: "avons servi", vous: "avez servi", "ils/elles": "ont servi" }, imparfait: { je: "servais", tu: "servais", "il/elle": "servait", nous: "servions", vous: "serviez", "ils/elles": "servaient" } },
  { infinitive: "ouvrir", level: "B1", present: { je: "ouvre", tu: "ouvres", "il/elle": "ouvre", nous: "ouvrons", vous: "ouvrez", "ils/elles": "ouvrent" }, passe_compose: { je: "ai ouvert", tu: "as ouvert", "il/elle": "a ouvert", nous: "avons ouvert", vous: "avez ouvert", "ils/elles": "ont ouvert" }, imparfait: { je: "ouvrais", tu: "ouvrais", "il/elle": "ouvrait", nous: "ouvrions", vous: "ouvriez", "ils/elles": "ouvraient" } },
  { infinitive: "offrir", level: "B1", present: { je: "offre", tu: "offres", "il/elle": "offre", nous: "offrons", vous: "offrez", "ils/elles": "offrent" }, passe_compose: { je: "ai offert", tu: "as offert", "il/elle": "a offert", nous: "avons offert", vous: "avez offert", "ils/elles": "ont offert" }, imparfait: { je: "offrais", tu: "offrais", "il/elle": "offrait", nous: "offrions", vous: "offriez", "ils/elles": "offraient" } },
  { infinitive: "souffrir", level: "B1", present: { je: "souffre", tu: "souffres", "il/elle": "souffre", nous: "souffrons", vous: "souffrez", "ils/elles": "souffrent" }, passe_compose: { je: "ai souffert", tu: "as souffert", "il/elle": "a souffert", nous: "avons souffert", vous: "avez souffert", "ils/elles": "ont souffert" }, imparfait: { je: "souffrais", tu: "souffrais", "il/elle": "souffrait", nous: "souffrions", vous: "souffriez", "ils/elles": "souffraient" } },
  { infinitive: "paraître", level: "B1", present: { je: "parais", tu: "parais", "il/elle": "paraît", nous: "paraissons", vous: "paraissez", "ils/elles": "paraissent" }, passe_compose: { je: "ai paru", tu: "as paru", "il/elle": "a paru", nous: "avons paru", vous: "avez paru", "ils/elles": "ont paru" }, imparfait: { je: "paraissais", tu: "paraissais", "il/elle": "paraissait", nous: "paraissions", vous: "paraissiez", "ils/elles": "paraissaient" } },
  { infinitive: "traduire", level: "B1", present: { je: "traduis", tu: "traduis", "il/elle": "traduit", nous: "traduisons", vous: "traduisez", "ils/elles": "traduisent" }, passe_compose: { je: "ai traduit", tu: "as traduit", "il/elle": "a traduit", nous: "avons traduit", vous: "avez traduit", "ils/elles": "ont traduit" }, imparfait: { je: "traduisais", tu: "traduisais", "il/elle": "traduisait", nous: "traduisions", vous: "traduisiez", "ils/elles": "traduisaient" } },
  { infinitive: "peindre", level: "B1", present: { je: "peins", tu: "peins", "il/elle": "peint", nous: "peignons", vous: "peignez", "ils/elles": "peignent" }, passe_compose: { je: "ai peint", tu: "as peint", "il/elle": "a peint", nous: "avons peint", vous: "avez peint", "ils/elles": "ont peint" }, imparfait: { je: "peignais", tu: "peignais", "il/elle": "peignait", nous: "peignions", vous: "peigniez", "ils/elles": "peignaient" } },
  { infinitive: "recevoir", level: "B1", present: { je: "reçois", tu: "reçois", "il/elle": "reçoit", nous: "recevons", vous: "recevez", "ils/elles": "reçoivent" }, passe_compose: { je: "ai reçu", tu: "as reçu", "il/elle": "a reçu", nous: "avons reçu", vous: "avez reçu", "ils/elles": "ont reçu" }, imparfait: { je: "recevais", tu: "recevais", "il/elle": "recevait", nous: "recevions", vous: "receviez", "ils/elles": "recevaient" } },
  { infinitive: "mourir", level: "B1", present: { je: "meurs", tu: "meurs", "il/elle": "meurt", nous: "mourons", vous: "mourez", "ils/elles": "meurent" }, passe_compose: { je: "suis mort", tu: "es mort", "il/elle": "est mort", nous: "sommes morts", vous: "êtes morts", "ils/elles": "sont morts" }, imparfait: { je: "mourais", tu: "mourais", "il/elle": "mourait", nous: "mourions", vous: "mouriez", "ils/elles": "mouraient" } },
  { infinitive: "naître", level: "B1", present: { je: "nais", tu: "nais", "il/elle": "naît", nous: "naissons", vous: "naissez", "ils/elles": "naissent" }, passe_compose: { je: "suis né", tu: "es né", "il/elle": "est né", nous: "sommes nés", vous: "êtes nés", "ils/elles": "sont nés" }, imparfait: { je: "naissais", tu: "naissais", "il/elle": "naissait", nous: "naissions", vous: "naissiez", "ils/elles": "naissaient" } },
  { infinitive: "apercevoir", level: "B1", present: { je: "aperçois", tu: "aperçois", "il/elle": "aperçoit", nous: "apercevons", vous: "apercevez", "ils/elles": "aperçoivent" }, passe_compose: { je: "ai aperçu", tu: "as aperçu", "il/elle": "a aperçu", nous: "avons aperçu", vous: "avez aperçu", "ils/elles": "ont aperçu" }, imparfait: { je: "apercevais", tu: "apercevais", "il/elle": "apercevait", nous: "apercevions", vous: "aperceviez", "ils/elles": "apercevaient" } },
  { infinitive: "défendre", level: "B1", present: { je: "défends", tu: "défends", "il/elle": "défend", nous: "défendons", vous: "défendez", "ils/elles": "défendent" }, passe_compose: { je: "ai défendu", tu: "as défendu", "il/elle": "a défendu", nous: "avons défendu", vous: "avez défendu", "ils/elles": "ont défendu" }, imparfait: { je: "défendais", tu: "défendais", "il/elle": "défendait", nous: "défendions", vous: "défendiez", "ils/elles": "défendaient" } },
  { infinitive: "permettre", level: "B1", present: { je: "permets", tu: "permets", "il/elle": "permet", nous: "permettons", vous: "permettez", "ils/elles": "permettent" }, passe_compose: { je: "ai permis", tu: "as permis", "il/elle": "a permis", nous: "avons permis", vous: "avez permis", "ils/elles": "ont permis" }, imparfait: { je: "permettais", tu: "permettais", "il/elle": "permettait", nous: "permettions", vous: "permettiez", "ils/elles": "permettaient" } },
  { infinitive: "promettre", level: "B1", present: { je: "promets", tu: "promets", "il/elle": "promet", nous: "promettons", vous: "promettez", "ils/elles": "promettent" }, passe_compose: { je: "ai promis", tu: "as promis", "il/elle": "a promis", nous: "avons promis", vous: "avez promis", "ils/elles": "ont promis" }, imparfait: { je: "promettais", tu: "promettais", "il/elle": "promettait", nous: "promettions", vous: "promettiez", "ils/elles": "promettaient" } },
  { infinitive: "valoir", level: "B1", present: { je: "vaux", tu: "vaux", "il/elle": "vaut", nous: "valons", vous: "valez", "ils/elles": "valent" }, passe_compose: { je: "ai valu", tu: "as valu", "il/elle": "a valu", nous: "avons valu", vous: "avez valu", "ils/elles": "ont valu" }, imparfait: { je: "valais", tu: "valais", "il/elle": "valait", nous: "valions", vous: "valiez", "ils/elles": "valaient" } },
  { infinitive: "falloir", level: "A2", present: { je: "", tu: "", "il/elle": "faut", nous: "", vous: "", "ils/elles": "" }, passe_compose: { je: "", tu: "", "il/elle": "a fallu", nous: "", vous: "", "ils/elles": "" }, imparfait: { je: "", tu: "", "il/elle": "fallait", nous: "", vous: "", "ils/elles": "" } },
  { infinitive: "pleuvoir", level: "A2", present: { je: "", tu: "", "il/elle": "pleut", nous: "", vous: "", "ils/elles": "" }, passe_compose: { je: "", tu: "", "il/elle": "a plu", nous: "", vous: "", "ils/elles": "" }, imparfait: { je: "", tu: "", "il/elle": "pleuvait", nous: "", vous: "", "ils/elles": "" } },
  { infinitive: "dépendre", level: "B1", present: { je: "dépends", tu: "dépends", "il/elle": "dépend", nous: "dépendons", vous: "dépendez", "ils/elles": "dépendent" }, passe_compose: { je: "ai dépendu", tu: "as dépendu", "il/elle": "a dépendu", nous: "avons dépendu", vous: "avez dépendu", "ils/elles": "ont dépendu" }, imparfait: { je: "dépendais", tu: "dépendais", "il/elle": "dépendait", nous: "dépendions", vous: "dépendiez", "ils/elles": "dépendaient" } },
  { infinitive: "prétendre", level: "B2", present: { je: "prétends", tu: "prétends", "il/elle": "prétend", nous: "prétendons", vous: "prétendez", "ils/elles": "prétendent" }, passe_compose: { je: "ai prétendu", tu: "as prétendu", "il/elle": "a prétendu", nous: "avons prétendu", vous: "avez prétendu", "ils/elles": "ont prétendu" }, imparfait: { je: "prétendais", tu: "prétendais", "il/elle": "prétendait", nous: "prétendions", vous: "prétendiez", "ils/elles": "prétendaient" } },
  { infinitive: "entreprendre", level: "B2", present: { je: "entreprends", tu: "entreprends", "il/elle": "entreprend", nous: "entreprenez", vous: "entreprenez", "ils/elles": "entreprennent" }, passe_compose: { je: "ai entrepris", tu: "as entrepris", "il/elle": "a entrepris", nous: "avons entrepris", vous: "avez entrepris", "ils/elles": "ont entrepris" }, imparfait: { je: "entreprenais", tu: "entreprenais", "il/elle": "entreprenait", nous: "entreprenions", vous: "entrepreniez", "ils/elles": "entreprenaient" } },
  { infinitive: "admettre", level: "B2", present: { je: "admets", tu: "admets", "il/elle": "admet", nous: "admettons", vous: "admettez", "ils/elles": "admettent" }, passe_compose: { je: "ai admis", tu: "as admis", "il/elle": "a admis", nous: "avons admis", vous: "avez admis", "ils/elles": "ont admis" }, imparfait: { je: "admettais", tu: "admettais", "il/elle": "admettait", nous: "admettions", vous: "admettiez", "ils/elles": "admettaient" } },
];

const allVerbs = verbData.map((v, i) => ({ id: i + 1, ...v }));

fs.writeFileSync(path.join(BOT_DIR, "verbs.json"), JSON.stringify(allVerbs, null, 2));
console.log(`✅ verbs.json: ${allVerbs.length} verbes`);

console.log("\n🎉 Données étendues avec succès !");
